steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/dogwood-terra-411701/cloudrun-nodejs:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dogwood-terra-411701/cloudrun-nodejs:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'dogwood-terra-411701', '--region=us-central1', '--platform=managed', '--image=gcr.io/dogwood-terra-411701/cloudrun-nodejs:$SHORT_SHA']
